In [1]:
import numpy as np
#Definimos la función 1 sobre la cual trabajaremos.
def camello(x,y):
  return(((4-2.1*x**2+(x**4)/3)*x**2)+x*y+(-4+4*y**2)*y**2)
def vector_aleatorio_normal(d):
  return np.random.normal(loc= 0,scale=1,size=d) 
def vector_aleatorio_normal_en_el_espacio_de_x(x,s,d):
    Q=x
    for y in Q:
      y=np.random.normal(y,s)
    return Q
def localcamello(n,s):
  #Iniciamos la imagen minima como el vector que la induce
  imagen=np.inf
  xfinal=np.zeros(2)
  x=vector_aleatorio_normal(1)
  y=vector_aleatorio_normal(1)
  #Realizamos el problema n veces
  for i in range(n):
    x=vector_aleatorio_normal_en_el_espacio_de_x(x,s,1)
    y=vector_aleatorio_normal_en_el_espacio_de_x(y,s,1)
    #Nuevamente, si la imagen de la iteración actual es menor a la anteriormente encontrada reasignamos la variable y guardamos el vector que la induce
    f=camello(x,y)
    if(f<imagen):
      imagen=f
      xfinal=np.array([x,y])
  #Regresamos la imagen y el vector que la induce en una lista    
  return [imagen,xfinal]

def localcamello_alterado(s,iteraciones,repeticiones):
  mejor=np.inf
  for i in range(repeticiones):
    A=localcamello(iteraciones,s)
    if(A[0]<mejor):
        mejor=A[0]
        x=A[1]
  return (mejor,x)

def tabular_camello_30_veces(s,iteraciones,repeticiones):
  L=[]
  for i in range(30):
    L.append(localcamello_alterado(s,iteraciones,repeticiones))
  print(L)
  return L
#sol=tabular_camello_30_veces(0.01,10000,100)

In [4]:
localcamello(10000,0.01)

[array([-1.02669221]),
 array([[-0.12569126],
        [ 0.71542808]])]

In [5]:
localcamello_alterado(0.01,10000,100)

(array([-1.03162468]),
 array([[-0.08967144],
        [ 0.71331387]]))

In [6]:
L=tabular_camello_30_veces(0.1,10000,100)
print(L)

[(array([-1.03162582]), array([[-0.08928809],
       [ 0.7122026 ]])), (array([-1.03159588]), array([[-0.08695325],
       [ 0.71229495]])), (array([-1.03159002]), array([[ 0.09234118],
       [-0.71148735]])), (array([-1.03162553]), array([[-0.09066606],
       [ 0.71289669]])), (array([-1.03162633]), array([[ 0.08942397],
       [-0.7130505 ]])), (array([-1.03161612]), array([[-0.09066384],
       [ 0.71161625]])), (array([-1.0316246]), array([[-0.09025704],
       [ 0.71205786]])), (array([-1.03161646]), array([[ 0.09006353],
       [-0.7138694 ]])), (array([-1.03160838]), array([[ 0.08757292],
       [-0.71238435]])), (array([-1.03161145]), array([[ 0.09055591],
       [-0.71405363]])), (array([-1.03160631]), array([[-0.08745288],
       [ 0.71258853]])), (array([-1.03161417]), array([[ 0.08929824],
       [-0.71135546]])), (array([-1.03162833]), array([[-0.08972278],
       [ 0.71274201]])), (array([-1.03158041]), array([[-0.09067319],
       [ 0.71505697]])), (array([-1.03160581]

In [29]:
import statistics as st
#Ahora encontramos la media de las imágenes y cada coordenada
import numpy as np
imagenescamello=[]
coordenadas=[]

for i in L:
    imagenescamello.append(i[0])
    coordenadas.append(i[1])
print("La imagen media es: ", np.mean(imagenescamello,axis=0))
print("La desviación estandar de las imágenes es:", np.std(imagenescamello))
print("La desviación estandar de las coordenadas es:", np.mean(coordenadas,axis=0))
print("La media de las coordenadas es:",np.std(coordenadas,axis=0))
print("El mejor minimo encontrado fue: ", min(imagenescamello))
print("La diferencia entre el real y el mejor encontrado es: ", -1.0316-min(imagenescamello))
print("La diferencia entre el real y el promedio es: ",-1.0316-np.mean(imagenescamello,axis=0))

La imagen media es:  [-1.03160977]
La desviación estandar de las imágenes es: 2.0925411469190135e-05
La desviación estandar de las coordenadas es: [[ 2.38980893e-05]
 [-2.74525899e-04]]
La media de las coordenadas es: [[0.08971163]
 [0.71244366]]
El mejor minimo encontrado fue:  [-1.03162833]
La diferencia entre el real y el mejor encontrado es:  [2.83278325e-05]
La diferencia entre el real y el promedio es:  [9.77142949e-06]
